name: deepjetLinux
channels:
- conda-forge
- NLeSC
- defaults
- https://conda.anaconda.org/NLeSC
dependencies:
- fftw=3.3.4=2
- gsl=1.16=2
- root=6.04=py3.4_gcc4.8.2
- root-numpy=4.4.0=root6.04_py3.4
- boost=1.63.0=py34_5
- boost-cpp=1.63.0=2
- bzip2=1.0.6=0
- icu=58.1=1
- mock=2.0.0=py34_0
- pbr=1.10.0=py34_0
- protobuf=3.1.0=py34_0
- tensorflow=0.12.1=py34_1
- cairo=1.14.8=0
- cloog=0.18.0=0
- dbus=1.10.10=0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- gcc=4.8.2=2
- glib=2.50.2=1
- gmp=6.1.0=0
- graphviz=2.38.0=4
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- h5py=2.6.0=np111py34_2
- harfbuzz=0.9.39=2
- hdf5=1.8.17=1
- isl=0.12.2=0
- jbig=2.1=0
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libtiff=4.0.6=3
- libtool=2.4.2=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- mkl=2017.0.1=0
- mpc=1.0.3=0
- mpfr=3.1.5=0
- numexpr=2.6.1=np111py34_2
- numpy=1.11.3=py34_0
- openssl=1.0.2k=0
- pango=1.40.3=1
- pcre=8.39=1
- pip=9.0.1=py34_1
- pixman=0.34.0=0
- pytables=3.3.0=np111py34_0
- python=3.4.5=0
- qt=4.8.7=4
- readline=6.2=2
- scikit-learn=0.18.1=np111py34_1
- scipy=0.18.1=np111py34_1
- setuptools=27.2.0=py34_0
- six=1.10.0=py34_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py34_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - cycler==0.10.0
  - keras==1.2.1
  - matplotlib==2.0.0
  - pyparsing==2.1.10
  - python-dateutil==2.6.0
  - pytz==2016.10
  - pyyaml==3.12
  - tables==3.3.0
  - theano==0.8.2

